### ISSUE TITLE
use localStorage to save favorite mentors

### ISSUE THREAD

**Issue by islamCodehood** [codehood-org/mentors-website#10]
- When the heart icon on a mentor's card clicked => this mentor should be saved in the localStorage.
- These favs should be shown by a toggle button.

**Comment by alex-whan** [comment]
Hello Islam! I'm working with a small team of devs and we'd love to take on issues #10 (this one) and #11 (which I'll also comment on) and contribute to CodeHood's Mentorship project! Just wanted to let you know - we'll be working on them tomorrow. We're on US Pacific Coast Time (GMT -7). Please let us know if you have any comments - and we'll fork/clone this and start working tomorrow, and will put in a PR when we're done.

**Comment by islamCodehood** [comment]
Hi Alex!

I replied to your comment  on issue #11 before this one.

**Comment by islamCodehood** [comment]
Hi @alex-whan 
Will you make a PR for this issue? 
The due date for the Mentor Filtration milestone is by 10-14.

**Comment by maccyber** [comment]
@Islam888: I would like to be assign to this, if it's not delivered.

We need an unique ID for the [mentors](https://github.com/codehood-org/mentors-website/blob/master/src/data/mentors.json), to keep track of the hearted mentors though.

**Comment by alex-whan** [comment]
> Hi @alex-whan
> Will you make a PR for this issue?
> The due date for the Mentor Filtration milestone is by 10-14.

Hi @Islam888 , I apologize for the wait on this. I can hopefully get a PR in tonight (GMT -7), if you don't mind waiting for it. However, if that is too late, it can be reassigned if you need it a bit sooner than that. Please let me know how to proceed.

**Comment by islamCodehood** [comment]
> > Hi @alex-whan
> > Will you make a PR for this issue?
> > The due date for the Mentor Filtration milestone is by 10-14.
> 
> Hi @Islam888 , I apologize for the wait on this. I can hopefully get a PR in tonight (GMT -7), if you don't mind waiting for it. However, if that is too late, it can be reassigned if you need it a bit sooner than that. Please let me know how to proceed.

Hi @alex-whan ! I received a PR from @maccyber yesterday. It is on the review. Thank you for your reply. Gonna open more issues if you and your team are interested.
Thanks

**Comment by alex-whan** [comment]
> > > Hi @alex-whan
> > > Will you make a PR for this issue?
> > > The due date for the Mentor Filtration milestone is by 10-14.
> > 
> > 
> > Hi @Islam888 , I apologize for the wait on this. I can hopefully get a PR in tonight (GMT -7), if you don't mind waiting for it. However, if that is too late, it can be reassigned if you need it a bit sooner than that. Please let me know how to proceed.
> 
> Hi @alex-whan ! I received a PR from @maccyber yesterday. It is on the review. Thank you for your reply. Gonna open more issues if you and your team are interested.
> Thanks

Hi Islam,

Thanks for letting me know - no problem. Would love to get in on some other issues soon. I will take a look at the repo and see if there is something my team and/or myself could work on.

Thanks!

Alex
