### ISSUE TITLE
Make flags clickable & use them to filter by country

### ISSUE THREAD

**Issue by islamCodehood** [codehood-org/mentors-website#11]
- The country flags on the upper right of mentors' cars should be clickable
- When clicked it should filter mentors by country.

**Comment by alex-whan** [comment]
Hello Islam! As I mentioned in my comment on issue #11, my team and I would love to work on this issue as well. We hope to put in a PR tomorrow on this feature. Please let us know if that is okay - and we'll proceed to get to work on this tomorrow.

**Comment by islamCodehood** [comment]
Hi Alex!
It is totally fine. Waiting your PR.
You should make a pull request on contribution branch.
