### ISSUE TITLE
Change App Title from React App to Codehood Mentors

### ISSUE THREAD

**Issue by mohamednajiub** [codehood-org/mentors-website#33]
![image](https://user-images.githubusercontent.com/22493564/95919985-dbeac980-0dae-11eb-85b5-0803f507e412.png)

**Comment by islamCodehood** [comment]
Hi @mohamednajiub 

Please, let it be **Codehood | Mentors**

**Comment by mohamednajiub** [comment]
Hi, @Islam888 

I updated it in #40
