### ISSUE TITLE
Search by mentor's name

### ISSUE THREAD

**Issue by elharony** [codehood-org/mentors-website#46]
When the list gets longer, it may be a good idea to search by the mentor's name

**Comment by islamCodehood** [comment]
Waiting your PR, @elharony .

Just take into consideration to cross-link it to the other filter options as done now between:
- skills
- country
- fav mentors.

Thanks

**Comment by elharony** [comment]
@Islam888 Thanks for this explanation.
I prefer to keep it unassigned to allow others to participate & fix it.
